version: '3' 

services:
  agent-server:
    build: ./provisioning
    image: agent
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=homestead
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - agent-server
